[project]
name = 'automated_carbon_credit'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.stx_carbon_credit]
path = 'contracts/stx_carbon_credit.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
